version: '2.2'
services:
  ## Config Servers
  config01:
    image: mongo
    command: mongod --port 28017 --bind_ip_all --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts
      - /talkative-microservices/config01:/data/db
  config02:
    image: mongo
    command: mongod --port 28018 --bind_ip_all --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts
      - /talkative-microservices/config02:/data/db
  config03:
    image: mongo
    command: mongod --port 28019 --bind_ip_all --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts
      - /talkative-microservices/config03:/data/db

  ## Shards
  shard01a:
    image: mongo
    command: mongod --port 29017 --bind_ip_all --shardsvr --replSet shard01
    volumes:
      - ./scripts:/scripts
      - /talkative-microservices/shard01a:/data/db
  shard02a:
    image: mongo
    command: mongod --port 29018 --bind_ip_all --shardsvr --replSet shard02
    volumes:
      - ./scripts:/scripts
      - /talkative-microservices/shard02a:/data/db
  shard03a:
    image: mongo
    command: mongod --port 29019 --bind_ip_all --shardsvr --replSet shard03
    volumes:
      - ./scripts:/scripts
      - /talkative-microservices/shard03a:/data/db

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --bind_ip_all --configdb configserver/config01:28017,config02:28018,config03:28019
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
      - /talkative-microservices/router:/data/db
      - /talkative-microservices/router_dump:/dump
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard02a
      - shard03a

  mongo-express:
    image: mongo-express
#    restart: always
    ports:
      - "8079:8081"
    links:
      - router:mongo

  mongoclient:
    image: mongoclient/mongoclient
    #    restart: always
#    environment:
#      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://router:27017
    ports:
      - "3000:3000"

  eureka-service:
    image: hronom/eureka-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8081"

networks:
  default:
    external:
      name: hronom
