version: '2.2'
services:
  mongodb:
    image: mongo:3.4.9
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:0.42.2
    ports:
      - "8079:8081"
    links:
      - mongodb:mongo

networks:
  default:
    external:
      name: hronom
